from finite_field_element import FiniteFieldElement
from elliptic_curve_point import EllipticCurvePoint

def main():
    p = 1021
    a = FiniteFieldElement(905, p)
    b = FiniteFieldElement(100, p)
    x = FiniteFieldElement(1006, p)
    y = FiniteFieldElement(416, p)
    generator = EllipticCurvePoint(x, y, a, b)
    curve_size = generator.get_curve_size(p)
    print(f"The curve has {curve_size} points")
    subgroup, order = generator.get_subgroup()
    print(f"The subgroup generated by the point {generator.print_info()} has order {order}")
    print(f"Cofactor: {curve_size}/{order} = {curve_size / order}")
    return

if __name__ == "__main__":
    main()